name       : python-google-auth-oauthlib
version    : 0.4.2
release    : 3
source     :
    - https://github.com/googleapis/google-auth-library-python-oauthlib/archive/v0.4.2.tar.gz : 41c2fe9dee780984928bc9f7e8c58cae450aa771aea353e2a65f7c5e4ffb8d75
license    : Apache-2.0
component  : programming.python
summary    : oauthlib integration for Google Auth
description: |
    This library provides oauthlib integration with google-auth
rundeps    :
    - python-google-auth
    - python-requests-oauthlib
build      : |
    %python3_setup
install    : |
    %python3_install
