name       : python-google-auth-oauthlib
version    : 0.4.1
release    : 1
source     :
    - https://github.com/googleapis/google-auth-library-python-oauthlib/archive/v0.4.1.tar.gz : db8ecd84088fee2e0cf2d7e32831756000135b745b49f83229ba71c9d00140cd
license    : Apache-2.0
component  : programming.python
summary    : oauthlib integration for Google Auth
description: |
    This library provides oauthlib integration with google-auth
rundeps  :
    - python-google-auth
    - python-requests-oauthlib
build      : |
    %python3_setup
install    : |
    %python3_install
